import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ApodProvider } from "@/contexts/ApodContext";
import { MarsProvider } from "@/contexts/MarsContext";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-w-[360px] text-slate-100 bg-slate-900`}
      >
        <div className="w-full relative overflow-hidden">
          <Header />
          <main>
            <ApodProvider>
              <MarsProvider>{children}</MarsProvider>
            </ApodProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
